select * from Artist;

select * from Album;

select  *
from Customer;

select
	FirstName as [Customer First Name],
	LastName as "Customer Last Name",
	Email
from Customer
order by FirstName, LastName DESC
LIMIT 5
;

select  *
from Customer
where SupportRepId = (
	SELECT max(SupportRepId) from Customer
)
;

select ArtistId
from Artist
where Name = 'Lolly';

-- Find all Albums of Barstow
select *
from Album
where ArtistId = (
		select ArtistId
		from Artist
		where Name = 'Barstow'
	);


-- how many customer's purchased two songs of 99 cents each?
select  *
from Invoice
where total = 1.98
ORDER by InvoiceDate
;

-- how many invoices exists between $.198 and $5?
select  *
from Invoice
where total BETWEEN 1.98 AND 5
ORDER by InvoiceDate
;


select  *
from Invoice
where total >= 1.98 AND  total <=  5
ORDER by InvoiceDate
;

-- How many invoices do we have that are exactly $1.98 or $3.96?
select  *
from Invoice
where total = 1.98 OR  total = 3.96
ORDER by InvoiceDate
;

select  *
from Invoice
where total in (1.98, 3.96)
ORDER by InvoiceDate
;

-- How many invoices were billed to the city of Brussels?
select  *
from Invoice
where BillingCity = 'Brussels'
ORDER by InvoiceDate
;

-- How many invoices were billed to the city of Brussels?
select  *
from Invoice
where BillingCity in ('Brussels', 'Orlando', 'Paris')
ORDER by InvoiceDate
;

--How many invoices were billed in the cities that start with B?
select  *
from Invoice
where BillingCity like ('B%')
ORDER by InvoiceDate
;


--How many invoices were billed in cities that have a B anywhere in its name?
select  *
from Invoice
where BillingCity like ('%B%')
ORDER by InvoiceDate
;

-- How many invoices were billed on May 22, 2010?
select  *
from Invoice
where InvoiceDate like '2010-05-22%'
ORDER by InvoiceDate
;

-- How many invoices were billed on May 22, 2010?
select  *, date(InvoiceDate) as date
from Invoice
where date(InvoiceDate) = '2010-05-22'
ORDER by InvoiceDate
;

-- Get a list of all invoices that were billed after May 22nd, 2010 and have a total of less than $3?
select  *, date(InvoiceDate) as date
from Invoice
where date(InvoiceDate) > '2010-05-22' and total < 3
ORDER by InvoiceDate
;

-- Get all invoices whose billing city starts with P or the billing city starts with D?
select  *, date(InvoiceDate) as date
from Invoice
where BillingCity like 'P%' OR BillingCity like 'D%'
ORDER by InvoiceDate
;

-- Get a list of all invoices that are greater than $1.98 from any cities whose names start with P or D?
SELECT  *, date(InvoiceDate) as date
FROM Invoice
WHERE total > 1.98
	AND (BillingCity like 'P%' OR BillingCity like 'D%')
ORDER by InvoiceDate
;

/*
Categories: -
- a baseline purchase, between 99 cent and 1.99,
- a low purchase falls between $2 and 6.99,
- the target purchase, between $7 and $15,
- a top performer above $15
*/

SELECT  *,
	CASE
		WHEN total < 2 THEN 'Baseline Purchase'
		WHEN total BETWEEN 2 AND  7 then 'Low Purchase'
		WHEN total BETWEEN 7  AND  15 then 'Target Purchase'
		ELSE 'Top Performer'
	END as PurchaseType

FROM Invoice
ORDER by InvoiceDate
;

-- Which cities do their top-performing sales come from?
SELECT  *,
	CASE
		WHEN total < 2 THEN 'Baseline Purchase'
		WHEN total BETWEEN 2 AND  7 then 'Low Purchase'
		WHEN total BETWEEN 7  AND  15 then 'Target Purchase'
		ELSE 'Top Performer'
	END as PurchaseType

FROM Invoice
WHERE PurchaseType = 'Top Performer'
ORDER by total DESC
;


-- Get a full list of customer names, first and last names, next to all the invoices generated by that customer?
SELECT  i.*, c.FirstName, c.LastName
FROM Invoice i, Customer c
WHERE i.CustomerId = c.CustomerId
ORDER by InvoiceDate
;

SELECT
	c.FirstName, c.LastName, i.InvoiceDate, i.BillingCity, i.total, c.Email
FROM
	Invoice i
INNER JOIN
	Customer c on c.CustomerId = i.CustomerId
ORDER by
	i.CustomerId, i.InvoiceDate
;


SELECT
	*
FROM
	Invoice
WHERE
	CustomerId = 6
;

SELECT
	*
FROM
	Invoice
WHERE
	CustomerId not in (
		SELECT CustomerId FROM Customer
	)
;

SELECT
	*
FROM
	Customer
WHERE
	CustomerId not in (
		SELECT CustomerId FROM Invoice
	)
;

SELECT
	*
FROM
	Customer
WHERE
	CustomerId = 6
;

SELECT  *
FROM Invoice i
JOIN Customer c on c.CustomerId = i.CustomerId
ORDER by InvoiceDate
;


-- Find employees that are responsible for the 10 highest individual sales to reward the employees?
SELECT
	i.*, e.FirstName, e.LastName, e.EmployeeId
FROM
	Invoice i
INNER JOIN Customer c on c.CustomerId = i.CustomerId
INNER JOIN Employee e on e.EmployeeId = c.SupportRepId
ORDER by total desc
LIMIT 10
;

-- How many customers do we have whose last name starts with S?
SELECT
	FirstName|| ' '||LastName as "Name", Address ||' , '|| City||' ' || State||', ' || PostalCode as [Mailing Address],
	length(postalcode) as size
FROM
	Customer
WHERE LastName like 'S%'
;


SELECT
	count(LastName)
FROM
	Customer
WHERE LastName like 's%'
;


-- Calculate an age of each employees?
SELECT
	EmployeeId, FirstName, LastName, BirthDate,
	strftime('%Y-%m-%d', BirthDate) as [Date Of Birth],
	strftime('%Y-%m-%d', 'now') as [Today],
	strftime('%Y-%m-%d', 'now')- strftime('%Y-%m-%d', BirthDate) as "Age",
	HireDate,
	strftime('%Y-%m-%d', HireDate) as [Hired On],
	Email
FROM
	Employee
;


-- Agreegate Functions
SELECT
	sum(total) [Total Sales], avg(total) [Average Sales], round(avg(total), 3) [Avg Sales], max(total) [Max Sales], min(total) [Min Sales], count(*) [Sales Count]
FROM
	Invoice
;


-- Get a list of the average amount customers spend by billing City?
SELECT
	BillingCity,  round(avg(total), 3) [Avg. Spend by City]
FROM
	Invoice
GROUP by BillingCity
ORDER by [Avg. Spend by City] desc
;


-- Get a list of the total spend by each customer?
SELECT
	c.FirstName, c.LastName, sum(i.total)
FROM
	Invoice i, Customer c
WHERE i.CustomerId = c.CustomerId
GROUP by i.CustomerId
;

-- What's an average invoice totals by city for only the cities that start with L?
SELECT
	BillingCity,  round(avg(total), 3) [Avg. Spend by City]
FROM
	Invoice
WHERE BillingCity like 'L%'
GROUP by BillingCity
ORDER by [Avg. Spend by City] desc
;

-- Find all average totals that are greater than $5?
SELECT
	BillingCity,  round(avg(total), 3) [Avg. Spend by City]
FROM
	Invoice
GROUP by BillingCity
HAVING [Avg. Spend by City] > 6
ORDER by [Avg. Spend by City] desc
;

-- Find all average totals that are greater than $6 and only for cities starting with 'b'?
SELECT
	BillingCity,  round(avg(total), 3) [Avg. Spend by City]
FROM
	Invoice
WHERE BillingCity like 'b%'
GROUP by BillingCity
HAVING [Avg. Spend by City] > 6
ORDER by [Avg. Spend by City] desc
;

-- What are the average invoice totals by billing country and city?
SELECT
	BillingCountry,	BillingCity,  round(avg(total), 2) [Avg. Spend by City]
FROM
	Invoice
GROUP by BillingCountry, BillingCity
HAVING [Avg. Spend by City] > 6
ORDER by BillingCountry, BillingCity, [Avg. Spend by City] DESC
;



SELECT
 	BillingCity, total, InvoiceDate
FROM
	Invoice
ORDER by  BillingCity
;

/*
How is each city performing against global average sales?
- Global Average Sales Amount
- Average Sales per City
*/
SELECT
	InvoiceDate,
	BillingCity,
	total
FROM
	Invoice
WHERE
	total < (
		SELECT
			round(avg(total), 2) [Global Average Sales Amount]
		FROM
			Invoice
	)
order by total DESC
;

SELECT
	BillingCity,
	round(avg(total), 2) [City Average Sales],
		(
		SELECT
			round(avg(total), 2)
		FROM
			Invoice
	)  as [Global Average Sales]
FROM
	Invoice
WHERE BillingCity is not NULL
GROUP by BillingCity
ORDER by BillingCity
;

-- Give us all the invoices that have occurred after this particular date?
SELECT
	*
FROM
	Invoice
WHERE date(InvoiceDate) > '2009-01-19'
;

-- Find, which tracks are not selling?

SELECT
	*
FROM
	Track
WHERE TrackId not in
	(
	SELECT
		DISTINCT TrackId
	FROM
		InvoiceLine
	)
;

SELECT
	*
FROM
	Track
;

-- Generate a report of all albums, their associated tracks, and the artists who sang them?
SELECT
	*
FROM
	Artist
;

SELECT
	*
FROM
	Album
;

SELECT
	*
FROM
	Track
;


SELECT
	*
FROM
	Artist a
INNER JOIN Album al on al.ArtistId = a.ArtistId
INNER JOIN Track t on t.AlbumId = al.AlbumId
;



-- Create a VIEW

CREATE VIEW V_AvgTotal AS
SELECT
	round(avg(total), 2)
FROM
	Invoice
;


SELECT
	*
FROM
	V_AvgTotal
;



-- Create a view with joins
CREATE VIEW V_InvoiceTracks AS
SELECT
	il.InvoiceId, il.TrackId, il.UnitPrice, il.Quantity,
	t.AlbumId,  t.Name, t.Composer, t.Milliseconds
FROM
	InvoiceLine il
INNER JOIN
	Track t on t.TrackId = il.TrackId
;

SELECT
	*
FROM
	V_InvoiceTracks

;


-- how many customers last-name starts with 'G'?
SELECT count(1)
from Customer
where LastName like 'G%'
;

-- which track appears at the top of the Track table when sorted in descending order?
select *
from Track
order by Name desc
;


-- how many tracks in the WSDA music database do not have a composer listed?


-- how many invoices were billed to the city of Brussels?
SELECT count(1)
FROM Invoice
WHERE BillingCity = 'Brussels'
;

